### ISSUE TITLE
Chinese Localization Improved

### ISSUE THREAD

**Issue by USS-Corvan** [paige404/CK3_Immortality#10]
The current Chinese localization is not machine translate, but let's face it: it's not good. Not only the punctuation symbols are not Chinese, the actual words even do not fully convey the meaning of the original text. (Not to mention there are even some text it didn't cover!) I have improved it, yet have no idea how to make a pull request. So I'll drop it here and maybe make a pull request later - when I've finally figured it out.

**Comment by USS-Corvan** [comment]
I've figured it out. I think.

**Comment by paige404** [comment]
Resolved in #12
