### ISSUE TITLE
Chinese Localization File Coding Problem

### ISSUE THREAD

**Issue by USS-Corvan** [paige404/CK3_Immortality#13]
There has been some problems since Ilast update. In short, the file code should be UTF-8 with BOM, yet it is currently UTF-8.

The files worked fine on my computer, yet when I was altering texts on the original Chinese localization file, github somehow decide that it should be UTF-8 instead of UTF-8 with BOM. Please alter it manually since I'm completely github-illiterate.

I've created a pull request which I think would work.

**Comment by AspirinEny** [comment]
🤣 idk if ur wrote it on purpose.. but it should called "UTF-8"

**Comment by USS-Corvan** [comment]
> 🤣 idk if ur wrote it on purpose.. but it should called "UTF-8"

Yeah that was on purpose.
No, just kidding. It's just a mistake.
