### ISSUE TITLE
No decisions other than “Give up your immortality” and “Choosing an age”

### ISSUE THREAD

**Issue by Folko-Ven** [paige404/CK3_Immortality#25]
Hi, I have no decisions other than “Give up your immortality” and “Choosing an age”. Game version 1.13.04
![1](https://github.com/user-attachments/assets/3b8dda9e-9941-4d9c-9ad5-d0fd5aa2f8a8)

**Comment by paige404** [comment]
Okay. That's pretty normal. Do you meet requirements that would proc other decisions? Did you engage in a once-in-a-lifetime kingdom invasion? Did you acquire a negative trait like an injury or an illness? 

Decisions only appear when they're relevant. Having the immortality trait, for instance, procs the Give Up Immortality decision—that decision will not appear at all of you aren't already immortal.

**Comment by Folko-Ven** [comment]
Man, I was so dumb! I thought all the decisions would be displayed at once, just grayed out if unavailable. I was just trying to create a sick character, and the necessary decisions finally appeared. Thank you so much for the mod and the quick response!
